---
language: node_js
node_js:
  - 7
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  local_dir: build
  repo: mvillis/mvillis.github.io
  target_branch: master
  fqdn: www.mikevillis.com
  email: mvillis@gmail.com
  name: Mike Villis
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
